
create table public.bot_users_id (
  tg_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  constraint users_id_pkey primary key (tg_id)
) TABLESPACE pg_default;

create table public.bot_users_settings (
  tg_id bigint generated by default as identity not null,
  language text null,
  notifications text null,
  constraint bot_users_settings_pkey primary key (tg_id)
) TABLESPACE pg_default;


create table public.game_sessions (
  session_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  players json null,
  session_status text null,
  constraint game_sessions_pkey primary key (session_id)
) TABLESPACE pg_default;

create table public.game_characters (
  tg_id bigint generated by default as identity not null,
  character_id bigint not null,
  created_at timestamp with time zone not null default now(),
  currently_active text not null default 'False'::text,
  character_name text null,
  constraint game_characters_pkey primary key (character_id)
) TABLESPACE pg_default;

create table public.game_characters_data (
  character_id bigint generated by default as identity not null,
  class text null,
  level bigint not null,
  xp bigint null,
  skills jsonb null,
  modifiers jsonb null,
  constraint game_characters_data_pkey primary key (character_id)
) TABLESPACE pg_default;

create table public.game_characters_inventory (
  character_id bigint generated by default as identity not null,
  item_id text null,
  set_id text null,
  stackable text null,
  amount bigint null,
  additional_data json null,
  constraint game_characters_inventory_pkey primary key (character_id)
) TABLESPACE pg_default;
