
create table public.bot_users_id (
  tg_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  constraint users_id_pkey primary key (tg_id)
) TABLESPACE pg_default;

create table public.bot_users_settings (
  tg_id bigint generated by default as identity not null,
  language text null,
  notifications text null,
  constraint bot_users_settings_pkey primary key (tg_id)
) TABLESPACE pg_default;


create table public.game_sessions (
  session_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  players json null,
  session_status text null,
  constraint game_sessions_pkey primary key (session_id)
) TABLESPACE pg_default;