
create table public.bot_users_id (
  tg_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  constraint users_id_pkey primary key (tg_id)
) TABLESPACE pg_default;

create table public.bot_users_settings (
  tg_id bigint generated by default as identity not null,
  language text null,
  notifications text null,
  constraint bot_users_settings_pkey primary key (tg_id)
) TABLESPACE pg_default;

create table public.game_user_currencies (
  tg_id bigint generated by default as identity not null,
  currency_name text not null default ''::text,
  value bigint null,
  constraint game_user_currencies_pkey primary key (tg_id)
) TABLESPACE pg_default;


create table public.game_sessions (
  session_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  players json null,
  session_status text null,
  constraint game_sessions_pkey primary key (session_id)
) TABLESPACE pg_default;

create table public.game_characters (
  tg_id bigint generated by default as identity not null,
  character_id bigint not null,
  created_at timestamp with time zone not null default now(),
  currently_active text not null default 'False'::text,
  character_name text null,
  constraint game_characters_pkey primary key (character_id)
) TABLESPACE pg_default;

create table public.game_characters_data (
  character_id bigint generated by default as identity not null,
  class text null,
  level bigint not null,
  xp bigint null,
  skills jsonb null,
  modifiers jsonb null,
  constraint game_characters_data_pkey primary key (character_id)
) TABLESPACE pg_default;

create table public.game_characters_inventory (
  character_id bigint generated by default as identity not null,
  item_id text null,
  set_id text null,
  stackable text null,
  amount bigint null,
  additional_data json null,
  constraint game_characters_inventory_pkey primary key (character_id)
) TABLESPACE pg_default;

create table public.game_characters_item_instances (
  instance_id text not null,
  character_id bigint not null,
  blueprint_id text not null,
  item_type text not null,
  quality bigint not null default 1,
  generated_effects jsonb not null,
  equipped_slot text null,
  equipped_index bigint null,
  additional_data jsonb null,
  constraint game_characters_item_instances_pkey primary key (instance_id)
) TABLESPACE pg_default;

create index game_characters_item_instances_character_idx
on public.game_characters_item_instances (character_id);

create table public.game_enemies_loottable (
  enemy_id text not null,
  item_id text not null,
  min_quantity bigint not null default '0'::bigint,
  max_quantity bigint not null,
  drop_rate real not null default '0.001'::real,
  constraint game_enemies_loottable_pkey primary key (enemy_id, item_id)
) TABLESPACE pg_default;
